#
platform :ios, '13.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles']

pre_install do |installer|
	unless installer.deployment?
		plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
	end
end

target 'VPNExample' do
    inherit! :search_paths
    pod 'SudoUser', '~> 8.0'
    pod 'SudoProfiles', '~> 7.1'
    pod 'SudoEntitlements', '~> 2.0'
    pod 'SudoVPN', '0.0.16-alpha'
    # pod 'SudoVPN', :path => '../ios'

    pod 'FlagKit'

    target 'VPNExampleTests'
end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  end
end
