#
platform :ios, '15.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source ENV['SUDOVPN_SDK_REPO']

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles']

pre_install do |installer|
	unless installer.deployment?
		plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
	end
end

target 'VPNExample' do
    inherit! :search_paths
    pod 'SudoUser', '~> 15.0'
    pod 'SudoProfiles', '~> 17.0'
    pod 'SudoEntitlements', '~> 9.0.1'
    pod 'SudoVPN',  '~> 16.0'

    pod 'FlagKit'

    target 'VPNExampleTests'
end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
