#
platform :ios, '15.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles']

pre_install do |installer|
	unless installer.deployment?
		plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
	end
end

target 'EmailExample' do
    pod 'SudoEntitlements', '~> 9.0'
    pod 'SudoUser', '~> 15.1'
    pod 'SudoProfiles', '~> 17.0'
    pod 'MimeParser', '~> 0.1'
    pod 'AWSCore', '~> 2.27.15'
    pod 'AWSAuthCore', '~> 2.27.15'
    pod 'AWSCognitoIdentityProvider', '~> 2.27.15'
    pod 'AWSCognitoIdentityProviderASF', '~> 2.27.15'
    pod 'AWSS3', '~> 2.27.15'

    target 'EmailExampleTests'

    pod 'SudoEmail', '~> 8.3.1'
end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end

  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
      end
  end
end
