#
platform :ios, '15.0'
use_frameworks!
use_modular_headers!

# inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoApiClient', 'SudoConfigManager', 'SudoEmail', 'SudoEmailNotificationExtension', 'SudoKeyManager', 'SudoLogging', 'SudoNotification', 'SudoNotificationExtension', 'SudoOperations', 'SudoProfiles']

plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude

target 'EmailExample' do
    pod 'SudoKeyManager', '~> 2.6', '>= 2.6.1'
    pod 'SudoEntitlements', '~> 11.0'
    pod 'SudoUser', '~> 16.0'
    pod 'SudoProfiles', '~> 18.0'
    pod 'SudoNotification', '~> 3.0'
    pod 'MimeParser', '~> 0.1'
    pod 'AWSAppSync', '~> 3.7.1'
    pod 'AWSCore', '~> 2.36.7'
    pod 'AWSAuthCore', '~> 2.36.7'
    pod 'AWSCognitoIdentityProvider', '~> 2.36.7'
    pod 'AWSCognitoIdentityProviderASF', '~> 2.36.7'
    pod 'AWSS3', '~> 2.36.7'

    target 'EmailExampleTests'

    pod 'SudoEmail', '~> 18.4.1'
end

target 'EmailExampleNotificationServiceExtension' do
    pod 'SudoNotificationExtension', '~> 2.1'
    pod 'SudoEmailNotificationExtension', '~> 14.4', '>= 14.4.1'

    target 'EmailExampleNotificationServiceExtensionTests'
end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
