platform :ios, '14.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoTelephony', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles']

pre_install do |installer|
  unless installer.deployment?
    plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
  end
end

target 'PasswordManagerExample' do
  pod 'SudoPasswordManager', '~> 6.0'
end

# supress warnings for pods
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
            config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
    end
end

