source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.2'

project 'DIRelayExample'
workspace 'DIRelayExample'

target 'DIRelayExample' do
  use_frameworks! :linkage => :static
  inhibit_all_warnings!

  # Pods for DIRelayExample
  pod 'SudoDIRelay', '~> 1.0.1'
  pod 'KeyManager', '~> 5.0.0'
  pod 'SudoLogging', '~> 0.3'
  pod 'SudoUser', '~> 12.1.3'

  target 'DIRelayExampleTests' do
     inherit! :search_paths
   end

end
