source 'https://cdn.cocoapods.org/'
source 'git@gitlab.tools.anonyome.com:anonyome/pod-repository.git'

platform :ios, '13.2'

project 'DIRelayExample'
workspace 'DIRelayExample'

target 'DIRelayExample' do
  use_frameworks! :linkage => :static
  inhibit_all_warnings!

  # Pods for DIRelayExample
  pod 'SudoDIRelay', :git=>'git@gitlab.tools.anonyome.com:platform/decentralized-identity/sudo-decentralized-identity-relay-ios.git', :branch=>'dev'
  pod 'KeyManager', '~> 5.0.0'
  pod 'SudoLogging', '~> 0.3'

  target 'DIRelayExampleTests' do
     inherit! :search_paths
   end

end
