source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

project 'DIRelayExample'
workspace 'DIRelayExample'

target 'DIRelayExample' do
  use_frameworks! :linkage => :static
  inhibit_all_warnings!

  # Pods for DIRelayExample
  pod 'SudoDIRelay', '~> 3.0'
  pod 'SudoUser', '~> 15.0'
  pod 'SudoProfiles', '~> 17.0'
  pod 'SudoEntitlements', '~> 9.0'

  target 'DIRelayExampleTests' do
     inherit! :search_paths
   end

end
