platform :ios, '15.0'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles']

pre_install do |installer|
    plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
end

target 'SiteReputationExample' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    pod 'SudoSiteReputation', '~> 5.0'

    # supress warnings for pods
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
                config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
            end
        end
    end
end
