source 'https://cdn.cocoapods.org/'

platform :ios, '13.2'

target 'DecentralizedIdentityExample' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Pods for DecentralizedIdentityExample
  pod 'SudoDecentralizedIdentity', '~> 3.0'
  pod 'Firebase/Firestore', '~> 6.23.0'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth', '~> 6.23.0'
end
