#
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoTelephony', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles', 'SudoIdentityVerification', 'SudoVirtualCards', 'SudoNotification', 'SudoNotificationExtension', 'SudoVirtualCardsNotificationExtension']

plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude

# PhoneNumberKit has stopped publishing Cocoapods releases to Public Registry
# This workaround enables application to get the releases straight from source repository 
#
# Needed by Frames at a version previous to 4.0
pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit', :tag => '3.7.6'

target 'VirtualCardsExample' do
    pod 'Plaid', '~> 4.2'
    pod 'Stripe', '~> 23'
    pod 'Frames', '~> 4'
    pod 'SudoUser', '~> 16.0'
    pod 'SudoProfiles', '~> 18.0'
    pod 'SudoEntitlements', '~> 11.0'
    pod 'SudoIdentityVerification', '~> 16.0'
    pod 'SudoNotification', '~> 3.0'
    pod 'SudoVirtualCards', '~> 26.2'

    target 'VirtualCardsExampleTests'
    target 'VirtualCardsExampleUITests'
end

target 'VirtualCardsExampleNotificationServiceExtension' do
    pod 'SudoNotificationExtension', '~> 3.0'
    pod 'SudoVirtualCardsNotificationExtension', '~> 26.1'

end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
      	config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
