#
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoTelephony', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles', 'SudoIdentityVerification', 'SudoVirtualCards']

pre_install do |installer|
	unless installer.deployment?
		plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
	end
end

target 'VirtualCardsExample' do
    pod 'Stripe', '~> 22'
    pod 'SudoUser', '~> 14.0'
    pod 'SudoProfiles', '~> 16.0'
    pod 'SudoEntitlements', '~> 8.0'
    pod 'SudoIdentityVerification', '~> 13.0'
    pod 'SudoVirtualCards', '~> 19.0'

    target 'VirtualCardsExampleTests'
end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
end
