platform :ios, '13.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoTelephony', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles', 'SudoIdentityVerification', 'SudoVirtualCards']

pre_install do |installer|
	unless installer.deployment?
		plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
	end
end

target 'VirtualCardsExample' do
    pod 'SudoUser', '~> 7.8'
    pod 'SudoIdentityVerification', '~> 4.7'
    pod 'SudoVirtualCards', '~> 8.0'
end

# Fix Xcode nagging warning on pod install/update
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
end
