platform :ios, '13.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

target 'TelephonyExample' do
    pod 'SudoUser', '~> 7.2'
    pod 'SudoTelephony', '~> 3.0'
end
