platform :ios, '13.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

acknowledgementsFields = ['name', 'version', 'licenseType', 'licenseText', 'homepage']
acknowledgementsExclude = ['SudoUser', 'SudoTelephony', 'SudoApiClient', 'SudoConfigManager', 'SudoKeyManager', 'SudoLogging', 'SudoOperations', 'SudoProfiles']

pre_install do |installer|
	unless installer.deployment?
		plugin 'cocoapods-acknowledgements', :fields => acknowledgementsFields, :exclude => acknowledgementsExclude
	end
end

target 'TelephonyExample' do
    #pod 'SudoTelephony', '~> 4.0.0'
    pod 'SudoTelephony' 
    pod 'SudoUser', '~> 12.0'
    pod 'SudoEntitlements'
end
